### PR TITLE
feat: Motasim.md

### PR DESCRIPTION
**Pull request by motasimmakki**

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Great Having you @motasimmakki

**Comment by motasimmakki** [comment]
> Great Having you @motasimmakki
Great to be a part of it, kindly invite me to join the organization too. 🙃

**Comment by AnirudhPanda** [comment]
> > Great Having you @motasimmakki
> > Great to be a part of it, kindly invite me to join the organization too. 🙃

Join Our Discord!!
We are inviting people soon!!

**Comment by motasimmakki** [comment]
> > > Great Having you @motasimmakki
> > > Great to be a part of it, kindly invite me to join the organization too. 🙃
> 
> Join Our Discord!!
> We are inviting people soon!!

sure, looking forward to dig more into open-source with org.

**Pull request merged**
